=== heikotroetsch/PP2/PP2/src/Uebung5/adressbuch.dtd
<!ELEMENT adressbuch (bezeichnung, adresse+)>

<!ELEMENT bezeichnung (#PCDATA)>

<!ELEMENT adresse (vorname, nachname, email, telefon, notiz?)>
<!ATTLIST adresse
          id ID #REQUIRED
>
<!ELEMENT email (#PCDATA)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT nachname (#PCDATA)>
<!ELEMENT notiz (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ATTLIST telefon
          land CDATA #IMPLIED
          vorwahl CDATA #REQUIRED
>
<!ENTITY at "@">

=== heikotroetsch/PP2/PP2/src/Uebung5/adressbuch-mit-DTD-extern.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE adressbuch SYSTEM "adressbuch.dtd">

<adressbuch>
<bezeichnung> <![CDATA[Mein Mein erstes <XML>Adressbuch]]></bezeichnung>
<adresse id="A1">
 <vorname> Max </vorname> 
<nachname>Müller</nachname>
<email>max&at; mueller.de </email>
<telefon land="+34" vorwahl="33??"> ??6669888 </telefon>
<notiz> Mein Box-Trainer</notiz>
</adresse>

<adresse id="A2">
 <vorname>Martina </vorname> 
<nachname>Kramer</nachname>
<email>martina &at; kramer.de </email>
<telefon land="D" vorwahl="34309"> 9229922</telefon>
<notiz> Meine Psychologin</notiz>
</adresse>

<adresse id="A3">
 <vorname>Toni </vorname> 
<nachname>Schmidt</nachname>
<email>tschmidt &at; uni-mannheim.de </email>
<telefon land="D" vorwahl="0621"> 1811818 </telefon>
</adresse>


</adressbuch>
